# Generated by Django 4.2.3 on 2023-07-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
