# Generated by Django 4.2.3 on 2023-07-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishow', '0002_alter_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
