# Generated by Django 4.2.3 on 2023-07-11 08:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vishow', '0003_stock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stock',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
